CREATE TABLE client
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT PK_CLIENT PRIMARY KEY (id)
);

CREATE TABLE project
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name      VARCHAR(255)                            NOT NULL,
    client_id BIGINT,
    CONSTRAINT PK_PROJECT PRIMARY KEY (id)
);

CREATE TABLE team
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255)                            NOT NULL,
    project_id BIGINT,
    CONSTRAINT PK_TEAM PRIMARY KEY (id)
);

CREATE TABLE team_member
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT PK_TEAM_MEMBER PRIMARY KEY (id)
);

CREATE TABLE team_member_team_link
(
    team_id        BIGINT NOT NULL,
    team_member_id BIGINT NOT NULL,
    CONSTRAINT PK_TEAM_MEMBER_TEAM_LINK PRIMARY KEY (team_id, team_member_id)
);

ALTER TABLE project
    ADD CONSTRAINT FK_PROJECT_ON_CLIENT FOREIGN KEY (client_id) REFERENCES client (id);

ALTER TABLE team_member_team_link
    ADD CONSTRAINT FK_TEAMEMTEA_ON_TEAM FOREIGN KEY (team_id) REFERENCES team (id);

ALTER TABLE team_member_team_link
    ADD CONSTRAINT FK_TEAMEMTEA_ON_TEAM_MEMBER FOREIGN KEY (team_member_id) REFERENCES team_member (id);

ALTER TABLE team
    ADD CONSTRAINT FK_TEAM_ON_PROJECT FOREIGN KEY (project_id) REFERENCES project (id);